-- local dracula = require("dracula")
-- dracula.setup({
--     colors = {
--         bg = "#050211"
--     },
--     italic_comment = false,
--     overrides = {},
--     transparent_bg = false,
--     show_end_of_buffer = false,
-- })
